spring:
  application:
    name: api-gateway
  zipkin:
      base-url: http://127.0.0.1:9411/
  sleuth:
      sampler:
        probability: 1
  cloud:
    gateway:
      routes:
        # Route cho Identity Service
        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/api/v1/auth/**

        # Route cho Product Service - Đọc dữ liệu
        - id: product-service-read
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
            - Method=GET

        # Route cho Product Service - Ghi dữ liệu
        - id: product-service-write
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
            - Method=POST,PUT,DELETE,OPTIONS
          filters:
            - name: AuthenticationFilter
            - name: RoleBasedAccessFilter
              args:
                requiredRoles: ADMIN, EMPLOYEE
                requiredPermissions: MANAGE_PRODUCTS

        # Route cho Order Service - Đặt hàng
        - id: order-place
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order
            - Method=POST,OPTIONS
          filters:
            - name: AuthenticationFilter

        # Route cho Order Service - Lấy đơn hàng theo ID
        - id: order-get-by-id
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order/{id}
            - Method=GET
          filters:
            - name: AuthenticationFilter
            - name: RoleBasedAccessFilter
              args:
                requiredRoles: CUSTOMER

        # Route cho Order Service - Lấy tất cả đơn hàng
        - id: order-get-all
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders
            - Method=GET
          filters:
            - name: AuthenticationFilter
            - name: RoleBasedAccessFilter
              args:
                requiredRoles: EMPLOYEE, ADMIN

        # Route cho PayPal Service
        - id: paypal-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/paypal/**
          filters:
            - name: AuthenticationFilter

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:3000"
            allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
            allowed-headers: "Content-Type, Authorization, Accept, Origin, X-Requested-With, X-Csrf-Token, If-Match"
            allow-credentials: true
            max-age: 3600

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1
server:
  port: 9191
